image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - ~/.cache
    - ~/.npm
    - build/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  VUE_APP_I18N_FALLBACK_LOCALE: de
  VUE_APP_I18N_SUPPORTED_LOCALE: en,de

stages:
  - test
  - doc
  - deploy

cypress:
  image: cypress/browsers:node14.17.0-chrome91-ff89
  stage: test
  script:
    - env | ( grep YAWIK || echo "ROUTER_BASE=/${CI_PAGES_URL#*://*/}/" )  > .env.local
    - yarn
    - node_modules/.bin/cypress cache list
    - node_modules/.bin/cypress info
    - yarn "test:e2e:ci"
  only:
    variables:
      - $YAWIK_RUN_CYPRESS == "yes"

mkdocs:
  stage: doc
  image: python:3.8-buster
  script:
    - pip install -r requirements.txt
    - mkdocs build --strict
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - env | ( grep YAWIK_ROUTER_BASE || echo "ROUTER_BASE=/${CI_PAGES_URL#*://*/}/" )  > .env.local
    - env | ( grep YAWIK || echo -n "" )  >> .env.local
    - yarn
    - yarn build
    - mkdir .public
    - cp -r dist/spa/* .public
    - cp -r build/docs .public
    - cp dist/spa/index.html .public/404.html
    - rm -Rf public
    - mv .public public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - master
